sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t damodarag/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true damodarag/docker-react npm run test
